spring:
  datasource:
    url: jdbc:mysql://localhost:3309/prueba_practica
    username: anthony
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8086