version: '3.8'
services:
  mysql-database:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: prueba_practica
      MYSQL_USER: anthony
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data_new:/var/lib/mysql

volumes:
  mysql_data_new:
